export const BANK_LIST_REQUEST = 'BANK_LIST_REQUEST'
export const BANK_LIST_SUCCESS = 'BANK_LIST_SUCCESS'
export const BANK_LIST_FAIL = 'BANK_LIST_FAIL'

export const BANK_DETAILS_REQUEST = 'BANK_DETAILS_REQUEST'
export const BANK_DETAILS_SUCCESS = 'BANK_DETAILS_SUCCESS'
export const BANK_DETAILS_FAIL = 'BANK_DETAILS_FAIL'